// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Tue Jul 08 16:42:05 2025

alien_draw alien_draw_inst
(
	.vga_driver_x_i(vga_driver_x_i_sig) ,	// input [9:0] vga_driver_x_i_sig
	.vga_driver_y_i(vga_driver_y_i_sig) ,	// input [9:0] vga_driver_y_i_sig
	.draw_o(draw_o_sig) 	// output  draw_o_sig
);

